# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'customer_signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(824, 756)
        MainWindow.setStyleSheet("background-color: rgb(85, 76, 70)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(130, 50, 571, 591))
        self.frame.setStyleSheet("background-color: rgb(255, 194, 53)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(190, 20, 191, 61))
        self.label.setStyleSheet("font-size: 30pt")
        self.label.setObjectName("label")
        self.fullname_lineedit = QtWidgets.QLineEdit(self.frame)
        self.fullname_lineedit.setGeometry(QtCore.QRect(100, 150, 171, 31))
        self.fullname_lineedit.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.fullname_lineedit.setObjectName("fullname_lineedit")
        self.email_lineedit = QtWidgets.QLineEdit(self.frame)
        self.email_lineedit.setGeometry(QtCore.QRect(100, 210, 171, 31))
        self.email_lineedit.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.email_lineedit.setObjectName("email_lineedit")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(330, 210, 171, 31))
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(200, 260, 171, 31))
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_5.setGeometry(QtCore.QRect(100, 310, 171, 31))
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_6.setGeometry(QtCore.QRect(310, 310, 171, 31))
        self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(210, 400, 171, 41))
        self.pushButton.setStyleSheet("background-color: rgb(255, 66, 66); font-size: 15pt")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(330, 150, 171, 31))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.lineEdit.setObjectName("lineEdit")
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setGeometry(QtCore.QRect(100, 360, 121, 20))
        self.checkBox.setObjectName("checkBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 824, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "𝑺𝒊𝒈𝒏 𝒖𝒑"))
        self.fullname_lineedit.setPlaceholderText(_translate("MainWindow", "First Name"))
        self.email_lineedit.setPlaceholderText(_translate("MainWindow", "Email"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Phone number"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "National code"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "Password"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "Re-Enter passwrod"))
        self.pushButton.setText(_translate("MainWindow", "Sign up"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Last Name"))
        self.checkBox.setText(_translate("MainWindow", "Show Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
