from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1248, 852)
        MainWindow.setStyleSheet("background-color: rgb(85, 76, 70)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1261, 881))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 371, 381))
        self.frame_2.setStyleSheet("background-color: rgb(255, 194, 53)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(60, 30, 271, 41))
        self.label.setStyleSheet("font-size: 25pt")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(10, 140, 271, 21))
        self.label_2.setStyleSheet("font-size: 10pt")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(290, 140, 71, 22))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(10, 200, 271, 21))
        self.label_3.setStyleSheet("font-size: 10pt")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(10, 260, 271, 21))
        self.label_4.setStyleSheet("font-size: 10pt")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(10, 320, 271, 21))
        self.label_5.setStyleSheet("font-size: 10pt")
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(290, 200, 71, 22))
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(290, 260, 71, 22))
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(290, 320, 71, 22))
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 371, 381))
        self.frame_3.setStyleSheet("background-color: rgb(255, 194, 53)")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(60, 30, 271, 41))
        self.label_11.setStyleSheet("font-size: 25pt")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setGeometry(QtCore.QRect(10, 140, 271, 21))
        self.label_12.setStyleSheet("font-size: 10pt")
        self.label_12.setObjectName("label_12")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_6.setGeometry(QtCore.QRect(290, 140, 71, 22))
        self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        self.label_13.setGeometry(QtCore.QRect(10, 200, 271, 21))
        self.label_13.setStyleSheet("font-size: 10pt")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setGeometry(QtCore.QRect(10, 260, 271, 21))
        self.label_14.setStyleSheet("font-size: 10pt")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_3)
        self.label_15.setGeometry(QtCore.QRect(10, 320, 271, 21))
        self.label_15.setStyleSheet("font-size: 10pt")
        self.label_15.setObjectName("label_15")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_7.setGeometry(QtCore.QRect(290, 200, 71, 22))
        self.lineEdit_7.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_8.setGeometry(QtCore.QRect(290, 260, 71, 22))
        self.lineEdit_8.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_9.setGeometry(QtCore.QRect(290, 320, 71, 22))
        self.lineEdit_9.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.frame_4 = QtWidgets.QFrame(self.tab)
        self.frame_4.setGeometry(QtCore.QRect(10, 390, 371, 381))
        self.frame_4.setStyleSheet("background-color: rgb(255, 194, 53)")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_16 = QtWidgets.QLabel(self.frame_4)
        self.label_16.setGeometry(QtCore.QRect(50, 40, 271, 41))
        self.label_16.setStyleSheet("font-size: 25pt")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_4)
        self.label_17.setGeometry(QtCore.QRect(10, 140, 271, 21))
        self.label_17.setStyleSheet("font-size: 10pt")
        self.label_17.setObjectName("label_17")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_10.setGeometry(QtCore.QRect(290, 140, 71, 22))
        self.lineEdit_10.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_19 = QtWidgets.QLabel(self.frame_4)
        self.label_19.setGeometry(QtCore.QRect(10, 260, 271, 21))
        self.label_19.setStyleSheet("font-size: 10pt")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.frame_4)
        self.label_20.setGeometry(QtCore.QRect(10, 320, 271, 21))
        self.label_20.setStyleSheet("font-size: 10pt")
        self.label_20.setObjectName("label_20")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_11.setGeometry(QtCore.QRect(290, 200, 71, 22))
        self.lineEdit_11.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_12.setGeometry(QtCore.QRect(290, 260, 71, 22))
        self.lineEdit_12.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_13.setGeometry(QtCore.QRect(290, 320, 71, 22))
        self.lineEdit_13.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_18 = QtWidgets.QLabel(self.frame_4)
        self.label_18.setGeometry(QtCore.QRect(10, 200, 271, 21))
        self.label_18.setStyleSheet("font-size: 10pt")
        self.label_18.setObjectName("label_18")
        self.frame_5 = QtWidgets.QFrame(self.tab)
        self.frame_5.setGeometry(QtCore.QRect(380, 10, 441, 381))
        self.frame_5.setStyleSheet("background-color: rgb(255, 194, 53)")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_21 = QtWidgets.QLabel(self.frame_5)
        self.label_21.setGeometry(QtCore.QRect(10, 30, 421, 41))
        self.label_21.setStyleSheet("font-size: 25pt")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame_5)
        self.label_22.setGeometry(QtCore.QRect(40, 140, 271, 21))
        self.label_22.setStyleSheet("font-size: 10pt")
        self.label_22.setObjectName("label_22")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_14.setGeometry(QtCore.QRect(340, 140, 71, 22))
        self.lineEdit_14.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_23 = QtWidgets.QLabel(self.frame_5)
        self.label_23.setGeometry(QtCore.QRect(40, 260, 271, 21))
        self.label_23.setStyleSheet("font-size: 10pt")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame_5)
        self.label_24.setGeometry(QtCore.QRect(40, 320, 271, 21))
        self.label_24.setStyleSheet("font-size: 10pt")
        self.label_24.setObjectName("label_24")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_15.setGeometry(QtCore.QRect(340, 200, 71, 22))
        self.lineEdit_15.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_16.setGeometry(QtCore.QRect(340, 260, 71, 22))
        self.lineEdit_16.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_17.setGeometry(QtCore.QRect(340, 320, 71, 22))
        self.lineEdit_17.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_25 = QtWidgets.QLabel(self.frame_5)
        self.label_25.setGeometry(QtCore.QRect(40, 200, 271, 21))
        self.label_25.setStyleSheet("font-size: 10pt")
        self.label_25.setObjectName("label_25")
        self.frame_6 = QtWidgets.QFrame(self.tab)
        self.frame_6.setGeometry(QtCore.QRect(380, 390, 441, 381))
        self.frame_6.setStyleSheet("background-color: rgb(255, 194, 53)")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_26 = QtWidgets.QLabel(self.frame_6)
        self.label_26.setGeometry(QtCore.QRect(130, 40, 171, 41))
        self.label_26.setStyleSheet("font-size: 25pt")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.frame_6)
        self.label_27.setGeometry(QtCore.QRect(40, 140, 271, 21))
        self.label_27.setStyleSheet("font-size: 10pt")
        self.label_27.setObjectName("label_27")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_18.setGeometry(QtCore.QRect(340, 140, 71, 22))
        self.lineEdit_18.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.label_28 = QtWidgets.QLabel(self.frame_6)
        self.label_28.setGeometry(QtCore.QRect(40, 260, 271, 21))
        self.label_28.setStyleSheet("font-size: 10pt")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.frame_6)
        self.label_29.setGeometry(QtCore.QRect(40, 320, 271, 21))
        self.label_29.setStyleSheet("font-size: 10pt")
        self.label_29.setObjectName("label_29")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_19.setGeometry(QtCore.QRect(340, 200, 71, 22))
        self.lineEdit_19.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_20.setGeometry(QtCore.QRect(340, 260, 71, 22))
        self.lineEdit_20.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_21.setGeometry(QtCore.QRect(340, 320, 71, 22))
        self.lineEdit_21.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.label_30 = QtWidgets.QLabel(self.frame_6)
        self.label_30.setGeometry(QtCore.QRect(40, 200, 271, 21))
        self.label_30.setStyleSheet("font-size: 10pt")
        self.label_30.setObjectName("label_30")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(10, 770, 141, 31))
        self.pushButton.setStyleSheet("background-color: rgb(255, 66, 66); font-size: 15pt")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 770, 131, 31))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 66, 66); font-size: 15pt")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(680, 770, 141, 31))
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 66, 66); font-size: 15pt")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setGeometry(QtCore.QRect(840, 770, 151, 31))
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 66, 66); font-size: 15pt")
        self.pushButton_4.setObjectName("pushButton_4")
        self.frame_7 = QtWidgets.QFrame(self.tab)
        self.frame_7.setGeometry(QtCore.QRect(840, 280, 381, 491))
        self.frame_7.setStyleSheet("background-color: rgb(255, 194, 53)")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.listView = QtWidgets.QListView(self.frame_7)
        self.listView.setGeometry(QtCore.QRect(0, 0, 381, 741))
        self.listView.setObjectName("listView")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(330, 770, 161, 31))
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 66, 66); font-size: 10pt")
        self.pushButton_5.setObjectName("pushButton_5")
        self.frame_9 = QtWidgets.QFrame(self.tab)
        self.frame_9.setGeometry(QtCore.QRect(839, 50, 381, 221))
        self.frame_9.setStyleSheet("background-color: rgb(255, 194, 53)")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_9)
        self.textBrowser.setGeometry(QtCore.QRect(0, 1, 381, 221))
        self.textBrowser.setObjectName("textBrowser")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_30.setGeometry(QtCore.QRect(840, 10, 131, 31))
        self.lineEdit_30.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(1070, 10, 151, 31))
        self.pushButton_6.setStyleSheet("background-color: rgb(255, 66, 66); font-size: 15pt")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab)
        self.pushButton_7.setGeometry(QtCore.QRect(520, 770, 141, 31))
        self.pushButton_7.setStyleSheet("background-color: rgb(255, 66, 66); font-size: 15pt")
        self.pushButton_7.setObjectName("pushButton_7")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame = QtWidgets.QFrame(self.tab_2)
        self.frame.setGeometry(QtCore.QRect(330, 140, 561, 531))
        self.frame.setStyleSheet("background-color: rgb(255, 194, 53)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_31 = QtWidgets.QLabel(self.frame)
        self.label_31.setGeometry(QtCore.QRect(150, 40, 281, 41))
        self.label_31.setStyleSheet("font-size: 25pt")
        self.label_31.setObjectName("label_31")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.frame_8 = QtWidgets.QFrame(self.tab_5)
        self.frame_8.setGeometry(QtCore.QRect(290, 110, 701, 581))
        self.frame_8.setStyleSheet("background-color: rgb(255, 194, 53)")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_22.setGeometry(QtCore.QRect(170, 200, 151, 31))
        self.lineEdit_22.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.lineEdit_22.setText("")
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_23.setGeometry(QtCore.QRect(390, 200, 151, 31))
        self.lineEdit_23.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_24.setGeometry(QtCore.QRect(390, 260, 151, 31))
        self.lineEdit_24.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_25.setGeometry(QtCore.QRect(390, 320, 151, 31))
        self.lineEdit_25.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_28.setGeometry(QtCore.QRect(170, 320, 151, 31))
        self.lineEdit_28.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_29.setGeometry(QtCore.QRect(170, 260, 151, 31))
        self.lineEdit_29.setStyleSheet("background-color: rgb(255, 255, 255); font-size: 10pt")
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_8.setGeometry(QtCore.QRect(290, 390, 141, 31))
        self.pushButton_8.setStyleSheet("background-color: rgb(255, 66, 66); font-size: 15pt")
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_32 = QtWidgets.QLabel(self.frame_8)
        self.label_32.setGeometry(QtCore.QRect(140, 60, 441, 61))
        self.label_32.setStyleSheet("font-size: 25pt")
        self.label_32.setObjectName("label_32")
        self.tabWidget.addTab(self.tab_5, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionEditing_profile = QtWidgets.QAction(MainWindow)
        self.actionEditing_profile.setObjectName("actionEditing_profile")
        self.actionProfile = QtWidgets.QAction(MainWindow)
        self.actionProfile.setObjectName("actionProfile")
        self.actionMenu = QtWidgets.QAction(MainWindow)
        self.actionMenu.setObjectName("actionMenu")
        self.actionOrder_Food = QtWidgets.QAction(MainWindow)
        self.actionOrder_Food.setObjectName("actionOrder_Food")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/fugue-icons-3.5.6/icons/printer-monochrome.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrint.setIcon(icon)
        self.actionPrint.setObjectName("actionPrint")
        self.actionBell = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/fugue-icons-3.5.6/icons/bell.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBell.setIcon(icon1)
        self.actionBell.setObjectName("actionBell")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "𝑨𝑷𝑷𝑬𝑻𝑰𝒁𝑬𝑹𝑺"))
        self.label_2.setText(_translate("MainWindow", "𝑺𝒑𝒊𝒄𝒚 𝑳𝒐𝒃𝒔𝒕𝒆𝒓------------------19.00"))
        self.label_3.setText(_translate("MainWindow", "𝑩𝒂𝒌𝒆𝒅 𝑬𝒔𝒄𝒂𝒓𝒈𝒐𝒕--------------16.00"))
        self.label_4.setText(_translate("MainWindow", "𝑺𝒉𝒓𝒊𝒎𝒑 𝑪𝒐𝒄𝒌𝒕𝒂𝒊𝒍--------------16.00"))
        self.label_5.setText(_translate("MainWindow", "𝑺𝒆𝒂𝒓𝒆𝒅 𝑨𝒉𝒊 𝑻𝒖𝒏𝒂-------------17.00"))
        self.label_11.setText(_translate("MainWindow", "𝑨𝑷𝑷𝑬𝑻𝑰𝒁𝑬𝑹𝑺"))
        self.label_12.setText(_translate("MainWindow", "𝑺𝒑𝒊𝒄𝒚 𝑳𝒐𝒃𝒔𝒕𝒆𝒓------------------19.00"))
        self.label_13.setText(_translate("MainWindow", "𝑩𝒂𝒌𝒆𝒅 𝑬𝒔𝒄𝒂𝒓𝒈𝒐𝒕--------------16.00"))
        self.label_14.setText(_translate("MainWindow", "𝑺𝒉𝒓𝒊𝒎𝒑 𝑪𝒐𝒄𝒌𝒕𝒂𝒊𝒍--------------16.00"))
        self.label_15.setText(_translate("MainWindow", "𝑺𝒆𝒂𝒓𝒆𝒅 𝑨𝒉𝒊 𝑻𝒖𝒏𝒂-------------17.00"))
        self.label_16.setText(_translate("MainWindow", "𝑺𝑻𝑬𝑨𝑲 𝑪𝑼𝑻𝑺"))
        self.label_17.setText(_translate("MainWindow", "𝑭𝒊𝒍𝒆𝒕 𝑴𝒊𝒈𝒏𝒐𝒏, 𝟖 𝒐𝒖𝒏𝒄𝒆-------36.00"))
        self.label_19.setText(_translate("MainWindow", "𝑹𝒊𝒃 𝑬𝒚𝒆 𝑺𝒕𝒆𝒂𝒌, 𝟏𝟖 𝒐𝒖𝒏𝒄𝒆----39.00"))
        self.label_20.setText(_translate("MainWindow", "𝑷𝒐𝒓𝒕𝒆𝒓𝒉𝒐𝒖𝒔𝒆 𝒇𝒐𝒓 𝒕𝒘𝒐-------40.00"))
        self.label_18.setText(_translate("MainWindow", "𝑭𝒊𝒍𝒆𝒕 𝑴𝒊𝒈𝒏𝒐𝒏, 𝟏𝟐 𝒐𝒖𝒏𝒄𝒆-----40.00"))
        self.label_21.setText(_translate("MainWindow", "𝑺𝑨𝑳𝑨𝑫𝑺 𝑨𝑵𝑫 𝑺𝑶𝑼𝑷𝑺"))
        self.label_22.setText(_translate("MainWindow", "𝑺𝒑𝒊𝒏𝒂𝒄𝒉 𝑺𝒂𝒍𝒂𝒅-----------------9.50"))
        self.label_23.setText(_translate("MainWindow", "𝑭𝒓𝒆𝒏𝒄𝒉 𝑶𝒏𝒊𝒐𝒏 𝑺𝒐𝒖𝒑----------5.00"))
        self.label_24.setText(_translate("MainWindow", "𝑳𝒐𝒃𝒔𝒕𝒆𝒓 𝑩𝒊𝒔𝒒𝒖𝒆----------------8.00"))
        self.label_25.setText(_translate("MainWindow", "𝑪𝒂𝒑𝒓𝒆𝒔𝒆 𝑺𝒂𝒍𝒂𝒅-----------------8.50"))
        self.label_26.setText(_translate("MainWindow", "𝑫𝑹𝑰𝑵𝑲𝑺"))
        self.label_27.setText(_translate("MainWindow", "𝑻𝒆𝒂---------------------------------2.50"))
        self.label_28.setText(_translate("MainWindow", "𝑪𝒐𝒄𝒂--------------------------------2.00"))
        self.label_29.setText(_translate("MainWindow", "𝑶𝒓𝒂𝒏𝒈𝒆 𝑱𝒖𝒊𝒄𝒆--------------------4.00"))
        self.label_30.setText(_translate("MainWindow", "𝑪𝒐𝒇𝒇𝒆------------------------------3.50"))
        self.pushButton.setText(_translate("MainWindow", "𝑻𝒐𝒕𝒂𝒍"))
        self.pushButton_2.setText(_translate("MainWindow", "𝑹𝒆𝒄𝒆𝒊𝒑𝒕"))
        self.pushButton_3.setText(_translate("MainWindow", "𝑹𝒆𝒔𝒆𝒕"))
        self.pushButton_4.setText(_translate("MainWindow", "𝑬𝒙𝒊𝒕"))
        self.pushButton_5.setText(_translate("MainWindow", "𝑫𝒐𝒘𝒏𝒍𝒐𝒂𝒅 𝑹𝒆𝒄𝒆𝒊𝒑𝒕"))
        self.lineEdit_30.setPlaceholderText(_translate("MainWindow", "Search For Food"))
        self.pushButton_6.setText(_translate("MainWindow", "𝑺𝒆𝒂𝒓𝒄𝒉"))
        self.pushButton_7.setText(_translate("MainWindow", "𝑶𝒓𝒅𝒆𝒓"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Menu"))
        self.label_31.setText(_translate("MainWindow", "𝒀𝒐𝒖𝒓 𝑷𝒓𝒐𝒇𝒊𝒍𝒆"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Profile"))
        self.lineEdit_22.setPlaceholderText(_translate("MainWindow", "New FirstName"))
        self.lineEdit_23.setPlaceholderText(_translate("MainWindow", "New LastName"))
        self.lineEdit_24.setPlaceholderText(_translate("MainWindow", " New PhoneNum"))
        self.lineEdit_25.setPlaceholderText(_translate("MainWindow", "Re-Enter Password"))
        self.lineEdit_28.setPlaceholderText(_translate("MainWindow", "New Password"))
        self.lineEdit_29.setPlaceholderText(_translate("MainWindow", "New Email"))
        self.pushButton_8.setText(_translate("MainWindow", "𝑺𝒖𝒃𝒎𝒊𝒕"))
        self.label_32.setText(_translate("MainWindow", "𝑬𝒅𝒊𝒕𝒊𝒏𝒈 𝒀𝒐𝒖𝒓 𝑷𝒓𝒐𝒇𝒊𝒍𝒆"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Edit Profile"))
        self.actionEditing_profile.setText(_translate("MainWindow", "Editing profile"))
        self.actionProfile.setText(_translate("MainWindow", "Profile"))
        self.actionMenu.setText(_translate("MainWindow", "Menu"))
        self.actionOrder_Food.setText(_translate("MainWindow", "Order Food"))
        self.actionPrint.setText(_translate("MainWindow", "Print"))
        self.actionBell.setText(_translate("MainWindow", "Bell"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
